Add experience rewards
talentprotocol/web-dapp pull request #1423
Opened 2023-09-01 14:15 UTC by francisco-leal

2023-09-01 16:16 UTC, francisco-leal commented on config/routes/public_api_routes.rb
> +            resources :experience_rewards, only: [:index] do
this creates get `api/v1/experience_rewards` and POST/PUT `api/v1/experience_rewards/:uuid/claim`

2023-09-04 17:21 UTC, RubenSousaDinis requested changes
Some comments to discuss

2023-09-04 17:21 UTC, RubenSousaDinis commented on app/controllers/api/v1/public_api/experience_rewards_controller.rb
> +    reward = ExperienceReward.find_by(uuid: params[:experience_reward_id])
We already have a catch here: https://github.com/talentprotocol/web-dapp/blob/b34915e15ed8b354f49b3c2da636d38d1889ca48/app/controllers/api/v1/public_api/api_controller.rb#L60

You can remove the if/else.

```suggestion
    reward = ExperienceReward.find_by!(uuid: params[:experience_reward_id])
```

2023-09-04 17:21 UTC, RubenSousaDinis commented on app/controllers/api/v1/public_api/experience_rewards_controller.rb
> +        render json: {success: result}, status: :ok
This approach is not following our Public API standard. We should update it to be consistent. Creating the spec/doc will help to follow the standard

2023-09-04 17:21 UTC, RubenSousaDinis commented on app/controllers/api/v1/public_api/experience_rewards_controller.rb
> +        render json: {success: result}, status: :ok
The index endpoint is following the standard.

2023-09-04 17:21 UTC, RubenSousaDinis commented on app/controllers/api/v1/public_api/experience_rewards_controller.rb
> +  def claim
Missing authentication.  You can add the following before actions only for the claim endpoint

```
before_action :internal_only
before_action :authenticated_only
```

2023-09-04 17:35 UTC, francisco-leal commented on app/controllers/api/v1/public_api/experience_rewards_controller.rb
> +        render json: {success: result}, status: :ok
This endpoint already has specs 😄 where can I read the standard?

2023-09-04 17:36 UTC, francisco-leal commented on app/controllers/api/v1/public_api/experience_rewards_controller.rb
> +    reward = ExperienceReward.find_by(uuid: params[:experience_reward_id])
This allows me to send a specific message on this endpoint to help the frontend show a more meaningful message. (the message itself will still be improved)

2023-09-05 11:46 UTC, RubenSousaDinis reviewed
Some comments to discuss

2023-09-05 11:46 UTC, RubenSousaDinis commented on app/services/rewards/claim.rb
> +      ActiveRecord::Base.transaction do
Missing lock with stock check

2023-09-06 09:32 UTC, RubenSousaDinis commented on app/services/rewards/claim.rb
> +      ActiveRecord::Base.transaction do
https://api.rubyonrails.org/classes/ActiveRecord/Locking/Pessimistic.html. You can check some ways here to simplify the code.

```suggestion
 account.with_lock do
    # This block is called within a transaction,
    # account is already locked.
    account.balance -= 100
    account.save!
end

```

2023-09-06 09:34 UTC, RubenSousaDinis commented on app/services/rewards/claim.rb
> +        reward = @reward.type.constantize.lock("FOR UPDATE NOWAIT").find(@reward.id)
Let's try to be consistent and use private attr_readers. We're using this approach in most of the services

2023-09-06 12:50 UTC, francisco-leal commented on db/migrate/20230905111753_create_merch_codes.rb
> +      t.string :code
No need, not that relevant

2023-09-06 16:05 UTC, RubenSousaDinis approved these changes

2023-09-06 16:28 UTC, merged