Review Invite 3+ Friends quest
talentprotocol/web-dapp pull request #1700
Opened 2023-11-08 17:05 UTC by verdefred

## Summary

- Check if there are three invited friends everytime someone is verified (no matter how)
- Increase the XP reward to 2,000 XP
- Clean the quest for all core team members

## Notion link

https://www.notion.so/talentprotocol/Review-Invite-3-Friends-Quest-d59a10170a9444fba53535a84d49157d?pvs=4

## How to test?

## Notes

2023-11-08 17:52 UTC, RubenSousaDinis commented on lib/tasks/quests.rake
> +    puts "Cleaning quest to all core team members..."
Not sure I understood what we mean by cleaning

2023-11-08 17:52 UTC, RubenSousaDinis commented on lib/tasks/quests.rake
> +    puts "Cleaning quest to all core team members..."
We're creating new records not removing them

2023-11-08 17:53 UTC, verdefred commented on lib/tasks/quests.rake
> +    puts "Cleaning quest to all core team members..."
Put them as done

2023-11-09 09:03 UTC, RubenSousaDinis approved these changes

2023-11-09 09:38 UTC, RubenSousaDinis requested changes
Just remembered that we need to change the upsert quests task with the new XP amount

2023-11-09 10:55 UTC, verdefred commented
> Just remembered that we need to change the upsert quests task with the new XP amount

Good catch, fixed

2023-11-09 11:27 UTC, RubenSousaDinis approved these changes

2023-11-09 11:29 UTC, merged