Talent impersonation
talentprotocol/web-dapp pull request #562
Opened 2022-06-09 17:27 UTC by taru5

## Summary

This PR enables admins to impersonate any user in the system. It allows admins to view all pages a user would see and also allow them to edit profiles to figure out what users are missing in their profile and help them get through.
We keep track of all impersonations and added [Paper Trail](https://github.com/paper-trail-gem/paper_trail) in this PR to keep audits of the changes in the profile.

## Notion link

https://talentprotocol.notion.site/Allow-admins-to-Impersonate-users-7492fbf4f176491381f65f8a945506ae)

## How to test?

The URL to start impersonating a user is `/impersonate/{username}`. Impersonation is only enabled if the user is an admin and lasts for 30 minutes.

2022-06-15 15:09 UTC, RubenSousaDinis reviewed
Some files are not needed and would be good to add some specs

2022-06-15 15:09 UTC, RubenSousaDinis commented on test/models/impersonation_test.rb
> +class ImpersonationTest < ActiveSupport::TestCase
Remove file

2022-06-21 09:00 UTC, RubenSousaDinis requested changes
Some changes required. Overall is looking good. Also tested locally and I have some comments:

- [ ] We should have a way to stop impersonation the user (a button in the header will do it)
- [ ] We should prevent private information (messages and probably notifications) to be displayed when impersonating the user

2022-06-21 09:00 UTC, RubenSousaDinis commented on app/helpers/impersonations_helper.rb
> +module ImpersonationsHelper
Can be removed

2022-06-21 09:00 UTC, RubenSousaDinis commented on app/models/user.rb
> +
I'm not seeing this being used anywhere. Why do we need it?

2022-06-21 09:00 UTC, RubenSousaDinis commented on app/models/user.rb
> +  has_paper_trail ignore: [:updated_at]
Why are we ignoring the updated_at field?

2022-06-21 09:00 UTC, RubenSousaDinis commented on db/migrate/20220526171942_create_impersonations.rb
> +      t.integer :impersonated_id, null: false
Since this are foreign keys we should treat them accordingly. Missing index and foreign key

2022-06-21 09:00 UTC, RubenSousaDinis commented on app/controllers/messages_controller.rb
> +    if message_params[:message].blank? || is_user_impersonated?
This prevention is good! Just wondering if we should have a shared validation method in application controller that halts the execution of some endpoints if the user is being impersonated. In the controller we can use a before action to run the method. WDYT?

2022-06-21 09:00 UTC, RubenSousaDinis commented on app/controllers/messages_controller.rb
>    def index
Wondering if we should return empty results on this endpoint. We will show private messages if we don't do it. We can disable the messages tab, but the BE protection is always better.

2022-06-24 18:10 UTC, MinervaMcG commented on app/models/user.rb
> +  has_paper_trail ignore: [:updated_at]
Since we update the user on every activity or page visit, the updated_at column is updated, without actually updating another field. In order to restrict the audits in the case, I ignored the updated_at column.

2022-06-24 18:10 UTC, MinervaMcG commented on app/models/user.rb
> +
We can ignore these at this point

2022-06-28 10:40 UTC, RubenSousaDinis reviewed
I stopped seeing the button to impersonate. Left some more comments.

2022-06-28 10:40 UTC, RubenSousaDinis commented on app/controllers/impersonations_controller.rb
> +  def show
this should be a post request since we're changing the server state by creating records

2022-06-28 10:40 UTC, RubenSousaDinis commented on app/controllers/application_controller.rb
> +    User.where(username: cookies.signed[:impersonated]).first
```suggestion
    User.find_by(username: cookies.signed[:impersonated])
```

2022-06-28 10:40 UTC, RubenSousaDinis commented on app/controllers/impersonations_controller.rb
> +class ImpersonationsController < ApplicationController
Can you add request specs for the endpoints below?

2022-06-28 12:22 UTC, MinervaMcG commented on app/controllers/impersonations_controller.rb
> +  def show
If we change it to post, the admin won't be able to access this URL directly from the browser to start impersonating a user.

2022-07-05 09:44 UTC, RubenSousaDinis reviewed
Some small comments. Overall looks good. I also tested and it's working properly! Well done!

2022-07-05 09:44 UTC, RubenSousaDinis commented on app/assets/stylesheets/impersonations.scss
> +// Place all the styles related to the impersonations controller here.
Remove empty file

2022-07-05 10:57 UTC, MinervaMcG commented on spec/requests/api/v1/impersonations_spec.rb
> +        create_impersonation_request
It is not allowing us to add a signed cookie directly in the scenario, so had to call the create request first

2022-07-05 11:10 UTC, MinervaMcG commented on db/migrate/20220624180204_add_indexes_to_impersonations.rb
> +class AddIndexesToImpersonations < ActiveRecord::Migration[6.1]
@RubenSousaDinis Added foreign keys in this migration

2022-07-11 08:31 UTC, RubenSousaDinis commented on spec/requests/api/v1/impersonations_spec.rb
> +        create_impersonation_request
Ok, I was also not able to mock signed cookies

2022-07-26 08:23 UTC, RubenSousaDinis approved these changes
Great work!

2022-07-26 08:33 UTC, merged