Adds ens and wallet routes
talentprotocol/web-dapp pull request #646
Opened 2022-08-05 06:10 UTC by sujink1999

## Summary

This PR adds user profile routes for wallet_id and ens

## Notion link

 https://talentprotocol.notion.site/Wallet-addresses-pages-cfdb492a3210490aa2ca381fd8e64372

## How to test?

Migrate the DB changes
Try visiting a profile with the wallet id
Try updating a ens domain for a user from the Edit profile section and navigate to the profile using ens

2022-08-05 14:22 UTC, RubenSousaDinis reviewed
Left some comments. Overall the code looks good!

2022-08-05 14:22 UTC, RubenSousaDinis commented on app/packs/src/onchain/utils.js
> +    const name = await provider.lookupAddress(walletAddress);
Constant already defined above

```suggestion
    name = await provider.lookupAddress(walletAddress);
```

2022-08-05 14:22 UTC, RubenSousaDinis commented on app/packs/src/onchain/utils.js
> +import Addresses from "./addresses.json";
Not used

2022-08-05 14:22 UTC, RubenSousaDinis commented on db/migrate/20220805060322_add_ens_to_users.rb
> +    add_column :users, :ens, :string
I would call this field `ens_domain`. I think it will be more explicit for developers starting in web3

2022-08-05 16:22 UTC, francisco-leal reviewed
nice work!

2022-08-05 16:22 UTC, francisco-leal commented on app/packs/src/components/talent/Edit/About.jsx
> +      name && changeUserAttribute("ens", name);
I would consider this personal preference but I'm not a huge fan of doing this sort of things in-line. Javascript can already be a bit messy ahah so I always favour readability. What do you think of splitting it into an if
```js
if (name) {
  changeUserAttribute("ens", name);
}
```

2022-08-05 16:22 UTC, francisco-leal commented on db/migrate/20220805060322_add_ens_to_users.rb
> +    add_column :users, :ens, :string
I agree with going with `ens_domain`. I could see a future where we even turn this into its own model so we can support multiple domains, like nomspace

2022-08-08 16:35 UTC, RubenSousaDinis requested changes
I was testing this and found an issue. You need to add a constraint to the route (https://github.com/talentprotocol/web-dapp/blob/c083b6dcede26dfc3a78531e3d557f8a3c3bf28a/config/routes.rb#L120):

 `get "/u/:username" => "users#show", :as => "user", :constraints => {username: /[^\/]+/}`

2022-08-08 16:36 UTC, RubenSousaDinis commented
> I was testing this and found an issue. You need to add a constraint to the route (
> 
> https://github.com/talentprotocol/web-dapp/blob/c083b6dcede26dfc3a78531e3d557f8a3c3bf28a/config/routes.rb#L120
> 
> ):
> `get "/u/:username" => "users#show", :as => "user", :constraints => {username: /[^\/]+/}`

Basically the `.` is a special character in the urls formats and by default rails consider it a format splitting the param into two different params.

2022-08-10 10:00 UTC, RubenSousaDinis approved these changes
Great work!

2022-08-11 09:07 UTC, merged