feat: invites part of partnership or user
talentprotocol/web-dapp pull request #778
Opened 2022-11-06 15:36 UTC by shirleyodeng

## Summary

## Notion link

https://talentprotocol.notion.site/Invites-part-of-partnership-or-user-ef5f9f96b8c74734bc4daee05c86e8dd

## How to test?

## Notes

2022-11-06 20:18 UTC, shirleyodeng commented on app/services/invites/create.rb
> +      @user = params.fetch(:user, nil)
Changed this to a record rather than an ID to prevent a double query to the database

2022-11-07 11:47 UTC, RubenSousaDinis requested changes
Some comments yo consider above.

We also need to change this piece of code: 

https://github.com/talentprotocol/web-dapp/blob/8edd4007966660b7051f8f7b2556487363617db1/app/blueprints/user_blueprint.rb#L32-L39

```ruby
    field :invited_by do |user, _options|
      if user.invited
        {
          name: user.invited.user.name,
          profile_picture_url: user.invited.user.profile_picture_url
        }
      end
    end
```

2022-11-08 11:14 UTC, RubenSousaDinis commented on app/services/partnerships/create.rb
> +      Invites::Create.new(partnership: partnership, talent_invite: true).call
We need to specify the number of invites somehow. It's ok if the info comes from the json file.

2022-11-08 11:15 UTC, RubenSousaDinis commented on lib/tasks/partnerships.rake
> +  task :create_from_json, [:json_path] => :environment do |_t, args|
we still need the max_uses for the invite

2022-11-08 14:56 UTC, shirleyodeng commented on lib/tasks/partnerships.rake
> +  task :create_from_json, [:json_path] => :environment do |_t, args|
Fixed! https://github.com/talentprotocol/web-dapp/pull/778/commits/18c8b5495f07327453f57a259d358c33aa6dce46

2022-11-08 15:17 UTC, RubenSousaDinis approved these changes
Well done!

2022-11-08 15:17 UTC, merged