feat: support page for moderators
talentprotocol/web-dapp pull request #906
Opened 2023-01-31 09:19 UTC by helloiambguedes

## Summary

Added a support page for moderators where they can search and check data about the users

## Notion link

[Task](https://www.notion.so/talentprotocol/Creating-a-tool-or-recreating-a-role-to-see-more-info-on-user-profile-to-improve-support-experience-ebd333bc3c6c43d4a6cdf9744f6a8b28)

## How to test?

Access `/support`

## Notes

N/A

2023-01-31 09:29 UTC, francisco-leal commented on app/controllers/support_controller.rb
> +    user_ref = User.
You can use

```rb
User.find(params(:id) # will throw an error if it doesn't find anyone (which already happens on your code given that you do user_ref[0] on line 10.
User.find_by(id: params[:id]) # which will return nil if it doesn't find any user
```

2023-01-31 09:29 UTC, francisco-leal commented on app/controllers/support_controller.rb
> +      .where("talent_supporters.supporter_wallet_id = '#{@userData.wallet_id}'");
`.where(talent_supporters: { supporter_wallet_id: @userData.wallet_id})`

2023-01-31 09:29 UTC, francisco-leal commented on app/controllers/support_controller.rb
> +    @userData = user_ref[0];
This isn't really the userData, this is the user itself. I would refactor this to merge with my suggestion above:
```rb
def user_page
  @user = User.find_by(id: params[:id))
  @userData = UserBlueprint.render_as_json(@user, view: :with_pictures); # the blueprint is smart, so since you're only passing one object, it will only return one value
  #...
end
```

2023-01-31 09:29 UTC, francisco-leal commented on app/controllers/support_controller.rb
> +      .where(user_id: 2)
You probably don't want this hardcoded value

2023-01-31 09:37 UTC, francisco-leal commented on config/routes.rb
> +  end
This would be a more ruby way of doing these routes so that it allows for us to extend the 
```rb
resources :support, only: [:index] do # resources defines all the normal REST routes to access a resource, but we're adding a only index modifier
  get :search, to: "support#search"
  resources :users, only: [:show] # same as above but we only want the user/:id GET route
end
```

2023-01-31 10:25 UTC, francisco-leal approved these changes

2023-01-31 10:34 UTC, RubenSousaDinis commented on app/packs/src/components-v2/support/index.jsx
> +        utils.users.map(user => (
4 spaces instead of 2?

2023-01-31 14:02 UTC, RubenSousaDinis requested changes
Some changes are still needed. Also left some comments to discuss

2023-01-31 14:02 UTC, RubenSousaDinis commented on config/routes.rb
> +  constraints Clearance::Constraints::SignedIn.new { |user| user.moderator? } do
Admins should also be able to visit this page.

2023-01-31 15:18 UTC, helloiambguedes commented on app/controllers/support_controller.rb
> +    @supporteds = @user.portfolio
Was not in the Notion task, is it worth it?

2023-01-31 17:44 UTC, RubenSousaDinis commented on app/controllers/support_controller.rb
> +    @supporteds = @user.portfolio
I ended up understanding why you need the two sets of data.

2023-02-01 09:20 UTC, RubenSousaDinis approved these changes

2023-02-01 09:22 UTC, merged